import Categories.Adjoint
import Categories.Category
import Categories.Category.CCC
import Categories.Category.Construction.Arrow
import Categories.Category.Construction.Functors
import Categories.Category.Core
import Categories.Category.Discrete
import Categories.Category.Groupoid
import Categories.Category.Instance.Cats
import Categories.Category.Instance.Setoids
import Categories.Category.Instance.Sets
import Categories.Category.Monoidal
import Categories.Category.Monoidal.Properties
import Categories.Category.Product
import Categories.Category.Slice
import Categories.Category.SubCategory
import Categories.Comonad
import Categories.Diagram.Cone
import Categories.Diagram.Equalizer
import Categories.Diagram.Limit
import Categories.Diagram.Pullback
import Categories.Functor
import Categories.Functor.Algebra
import Categories.Functor.Bifunctor
import Categories.Functor.Coalgebra
import Categories.Functor.Core
import Categories.Functor.Hom
import Categories.Functor.Power
import Categories.Functor.Properties
import Categories.Kan
import Categories.Monad
import Categories.Morphism
import Categories.Morphism.IsoEquiv
import Categories.Morphism.Isomorphism
import Categories.Morphism.Properties
import Categories.NaturalTransformation
import Categories.NaturalTransformation.Core
import Categories.NaturalTransformation.NaturalIsomorphism
import Categories.Object.BinaryProducts
import Categories.Object.Coproduct
import Categories.Object.Duality
import Categories.Object.Exponential
import Categories.Object.Exponentials
import Categories.Object.Initial
import Categories.Object.Product
import Categories.Object.Product.Core
import Categories.Object.Product.Morphisms
import Categories.Object.Terminal
import Categories.Square
import Categories.Square.Core
import Categories.Square.Iso
import Categories.Utils.Product
